fixes #5
basic_demo.cpp:13:12: error: 'template<class> class vdk::signal'
conflicts with a previous declaration #5

https://github.com/vdksoft/signals/issues/5